### ISSUE TITLE
Note on branding

### ISSUE THREAD

**Issue by alexellis** [ewilde/faas-fargate#4]
Hi Ed,

> OpenFaas on AWS Fargate. Open source functions as a service without any infrastructure to manage

This should be written OpenFaaS

Might be good to use casing for: Functions as a Service

The project is now called faas-fargate on GitHub (nice logo btw!) but the page heading says faas-ecs.

Hope this is helpful

Alex

**Comment by ewilde** [comment]
@alexellis thank you for bringing this to my attention, should be corrected now
