### ISSUE TITLE
test: async support 

### ISSUE THREAD

**Issue by ewilde** [ewilde/faas-fargate#5]
- [ ] Test you can invoke a function [asynchronously](https://github.com/openfaas/faas/blob/master/guide/asynchronous.md), assuming this will work just want to make sure

**Comment by alexellis** [comment]
Got any more details? :-)

**Comment by ewilde** [comment]
@alexellis issue to test that the provider works with `async` function invocation

**Comment by ewilde** [comment]
https://github.com/ewilde/terraform-aws-openfaas-fargate/pull/7 fixes this issue
![image](https://user-images.githubusercontent.com/329397/47302375-44b46680-d619-11e8-81d4-64197b934029.png)

No changes were needed to OpenFaaS

**Comment by alexellis** [comment]
Nice progress with this! :ok:
